---

- name: Install Unbound
  ansible.builtin.apt:
    name: unbound
    state: present
    update_cache: true

- name: Ensure unbound include directory exists
  ansible.builtin.file:
    path: /etc/unbound/unbound.conf.d
    state: directory
    mode: "0755"

- name: Configure Unbound for Pi-hole
  ansible.builtin.template:
    src: pi-hole.conf.j2
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    mode: "0644"
  notify: Restart Unbound

- name: Download root hints file
  ansible.builtin.get_url:
    url: "{{ pihole_v6_unbound_root_hints_url }}"
    dest: /etc/unbound/root.hints
    mode: "0644"
  notify: Restart Unbound

- name: Ensure Unbound is enabled & running
  ansible.builtin.service:
    name: unbound
    enabled: true
    state: started
    daemon_reload: true
