---
- name: Install Configure Unbound | Install Unbound package
  ansible.builtin.apt:
    name: "{{ __pihole_v6_unbound_service_name }}"
    state: present
    update_cache: true

- name: Install Configure Unbound | Ensure include directory exists
  ansible.builtin.file:
    path: "/etc/unbound/unbound.conf.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install Configure Unbound | Deploy Pi-hole resolver configuration
  ansible.builtin.template:
    src: "pi-hole.conf.j2"
    dest: "/etc/unbound/unbound.conf.d/pi-hole.conf"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Pihole_v6 | Restart unbound service

- name: Install Configure Unbound | Download root hints
  ansible.builtin.get_url:
    url: "{{ pihole_v6_unbound_root_hints_url }}"
    dest: "/etc/unbound/root.hints"
    owner: root
    group: root
    mode: "0644"
  notify: Pihole_v6 | Restart unbound service

- name: Install Configure Unbound | Ensure Unbound service is enabled and running
  ansible.builtin.systemd:
    name: "{{ __pihole_v6_unbound_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
