---

- name: Allow Pi-hole v6 services
  ansible.builtin.import_role:
    name: ufw_profiles
  vars:
    ufw_profiles_catalog:
      - "{{ pihole_v6_ufw_profile }}"
    ufw_profiles_allow_applications:
      - "{{ pihole_v6_ufw_profile.name }}"
  when: pihole_v6_ufw_enable | bool
  tags: ['pihole_v6', 'ufw']

- name: Install Unbound
  ansible.builtin.import_tasks: install_configure_unbound.yml
  when: pihole_v6_install_unbound | bool
  tags: ['pihole_v6', 'unbound']

- name: Install Pi-hole
  ansible.builtin.import_tasks: install_configure_pihole.yml
  tags: ['pihole_v6', 'install']

- name: Manage Pi-hole adlists via API
  ansible.builtin.import_tasks: manage_pihole_api_lists.yml
  when: pihole_v6_adlists_present | length > 0
  tags: ['pihole_v6', 'lists']

- name: Configure Pi-hole TLS
  ansible.builtin.import_tasks: obtain_letsencrypt_certs.yml
  when: pihole_v6_enable_tls | bool
  tags: ['pihole_v6', 'tls']

- name: Update Pi-hole if installed
  ansible.builtin.command: pihole -up
  register: pihole_v6_up
  changed_when: "'up to date' not in (pihole_v6_up.stdout | lower)"
  failed_when: pihole_v6_up.rc != 0
  tags: ['pihole_v6', 'updates-patches']

- name: Trigger Pi-hole gravity update
  ansible.builtin.command: pihole -g
  register: pihole_v6_gravity
  changed_when: "'No changes detected' not in pihole_v6_gravity.stdout"
  failed_when: pihole_v6_gravity.rc != 0
  when: pihole_v6_trigger_gravity | bool
  tags: ['pihole_v6', 'updates-patches']

- name: Test Pi-hole
  ansible.builtin.import_tasks: test_pihole.yml
  when: pihole_v6_enable_tests | bool
  tags: ['pihole_v6', 'test']
