---
- name: Pihole_v6 | Restart unbound service
  ansible.builtin.systemd:
    name: "{{ __pihole_v6_unbound_service_name }}"
    state: restarted
    daemon_reload: true

- name: Pihole_v6 | Restart Pi-hole FTL service
  ansible.builtin.systemd:
    name: "{{ __pihole_v6_ftl_service_name }}"
    state: restarted
    daemon_reload: true

# command is required because Pi-hole does not provide a module for gravity updates.
- name: Pihole_v6 | Update gravity database
  ansible.builtin.command: pihole -g
  register: __pihole_v6_gravity_run
  changed_when: "'No changes detected' not in __pihole_v6_gravity_run.stdout"
  failed_when: __pihole_v6_gravity_run.rc != 0
  when:
    - pihole_v6_trigger_gravity | bool
    - not ansible_check_mode
